name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.12', '3.13']
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "2.3.4"

      - name: Install dependencies
        run: poetry install --extras "test"

      - name: Run tests
        run: poetry run pytest --color=yes --cov --cov-report=xml